require: 
  - rubocop-performance
  - rubocop-rails

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging

Rails/SkipsModelValidations:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - config/boot.rb
    - config.ru
    - config/application.rb
    - tmp/**/*
    - node_modules/**/*
  CacheRootDirectory: tmp/